version: '3.3'

volumes:
  postgres_data:

services:
  api:
    image: node:16
    container_name: api
    working_dir: /api
    restart: unless-stopped
    stdin_open: true
    command: bash -c "npm install && npm run start"
    environment:
      - NODE_ENV=development
      - PORT=3001
    ports:
      - '3001:3001'
    volumes:
      - ./api:/api

  
